include:
    #- ./mb-docker/docker-compose.yml
    - ./supabase/docker/docker-compose.yml
services:
    lib-node:
        build:
            context: .
            dockerfile: Dockerfile.lib
            target: lib-build-node
        image: mdv-lib-node
    lib-deno:
        build:
            context: .
            dockerfile: Dockerfile.lib
            target: lib-build-deno
        image: mdv-lib-deno
    frontend:
        environment:
            SB_URL: ${SB_URL}
            SB_ANON_KEY: ${SB_ANON_KEY}
            SB_SERVICE_KEY: ${SB_SERVICE_KEY}
            APP_URL: ${APP_URL}
            DATA_ACQ_URL: ${DATA_ACQ_URL}
            FRONTEND_LOG_LEVEL: ${FRONTEND_LOG_LEVEL}
            APPLE_MEDIA_KEY_PATH: ${APPLE_MEDIA_KEY_PATH}
            APPLE_MEDIA_KEY_ID: ${APPLE_MEDIA_KEY_ID}
            APPLE_TEAM_ID: ${APPLE_TEAM_ID}
        build:
            context: ./frontend/
            target: dev
        volumes:
            - ./lib/:/app/lib
            - ./frontend/src:/app/frontend/src
            - ./frontend/static:/app/frontend/static
            - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
            - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
            - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
            - ./frontend/.env.local:/app/frontend/.env.local
            - MQP:/data/frontend
        ports:
            - "5173:5173"
            - "24678:24678"
        networks:
            - default
        depends_on:
            - lib-node
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    data-acquisition:
        environment:
            APPLE_MEDIA_KEY_ID: ${APPLE_MEDIA_KEY_ID}
            APPLE_MEDIA_KEY_PATH: ${APPLE_MEDIA_KEY_PATH}
            APPLE_TEAM_ID: ${APPLE_TEAM_ID}
            APP_URL: ${APP_URL}
            DATA_ACQ_LOG_LEVEL: ${DATA_ACQ_LOG_LEVEL}
            SPOTIFY_CID: ${SPOTIFY_CID}
            SPOTIFY_SECRET: ${SPOTIFY_SECRET}
            SPOTIFY_REFRESH: ${SPOTIFY_REFRESH}
            SB_URL: ${SB_URL}
            SB_SERVICE_KEY: ${SB_SERVICE_KEY}
            SB_URL_TEST: ${SB_URL_TEST}
            DATA_ACQ_PORT: ${DATA_ACQ_PORT}
        build:
            context: ./data-acquisition/
            target: dev
        volumes:
            - MQP:/data/data-acquisition
        ports:
            - "3001:3001"
        networks:
            - default
        depends_on:
            db:
                condition: service_healthy
            analytics:
                condition: service_started
            redis:
                condition: service_started
            lib-deno:
                condition: service_started
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - kong
volumes:
    MQP:
